# This is a basic workflow to help you get started with Actions

name: RunRScriptAndPushData

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      
      # Setup R
      - name: Setup R
        uses: r-lib/actions/setup-r@master
      - name: Setup dependencies
        uses: r-lib/actions/setup-r-dependencies@master
        with:
          working-directory: './src/data_script'
        shell: Rscript {0}
      
      # Run RScript
      - name: Run Script
        run: Rscript ./src/data_script/github_action_hospinc.R
        
      - name: Commit and push data directory
        uses: EndBug/add-and-commit@v9
        with:
          add: './data/'
