# This is a basic workflow to help you get started with Actions

name: CreateAndDeployFlexdashboard

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      
      # Setup R
      - name: Setup R
        uses: r-lib/actions/setup-r@master
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@master
      - name: Setup dependencies
        run: install.packages(c('readr', 'openxlsx', 'dplyr', 'tidyr'), repos='http://cran.us.r-project.org')
        shell: Rscript {0}
      
      # Run RScript
      - name: Run Script
        run: ./scriptSrc/github_action_hospinc.R
        shell: Rscript {0}
        
      - name: Echo files
        run : "ls -la ./scriptSrc"
        
      - name: Echo root files
        run : "ls -la ."
          
      #- name: Push created data
  
